name: Reset instance
on:
  push:
    branches:
      - main
jobs:
  instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out cookiecutter-testn
        uses: actions/checkout@v2.3.4
        with:
          path: cookiecutter-test
      - name: Check out cookiecutter-test-instance
        uses: actions/checkout@v2.3.4
        with:
          repository: "cjolowicz/cookiecutter-test-instance"
          path: cookiecutter-test-instance
          token: ${{ secrets.X_GITHUB_TOKEN }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.7"
      - name: Install cookiecutter
        working-directory: cookiecutter-test
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt cookiecutter
      - name: Remove working tree
        run: |
          mv cookiecutter-test-instance/.git tmp.git
          rm -rf cookiecutter-test-instance
          mkdir cookiecutter-test-instance
          mv tmp.git cookiecutter-test-instance/.git
      - name: Invoke cookiecutter
        run: >-
          cookiecutter
          https://github.com/${GITHUB_REPOSITORY}
          --overwrite-if-exists
          --no-input
          project_name=cookiecutter-test-instance
      - name: Create commit
        run: |
          cd cookiecutter-test
          author="$(git show --no-patch --format='%an <%ae>')"
          date="$(git show --no-patch --format=%ad)"
          message="$(git show --no-patch --format=%B | sed 's/ *(#[0-9]\+)//g')

          Original-Commit: ${GITHUB_REPOSITORY}@${GITHUB_SHA::7}"

          cd ../cookiecutter-test-instance
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit --allow-empty --author="$author" --date="$date" --message="$message"
      - name: Push to instance
        run: >-
          git
          -C cookiecutter-test-instance
          push
          https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/cjolowicz/cookiecutter-test-instance.git
          HEAD:main
